export const ACTIONS = {
  SET_PROGRAMME_GAMES: '@programmes/SET_PROGRAMME_GAMES',
  SET_GAME_TIME: '@programmes/SET_GAME_TIME',
  SET_PROGRAMME_NAME: '@programmes/SET_PROGRAMME_NAME',

  LOAD_PROGRAMMES: '@programmes/LOAD_PROGRAMMES',
  LOAD_PROGRAMMES_SUCCESS: '@programmes/LOAD_PROGRAMMES_SUCCESS',
  LOAD_PROGRAMMES_FAIL: '@programmes/LOAD_PROGRAMMES_FAIL',

  LOAD_GAMES: '@programmes/LOAD_GAMES',
  LOAD_GAMES_SUCCESS: '@programmes/LOAD_GAMES_SUCCESS',
  LOAD_GAMES_FAIL: '@programmes/LOAD_GAMES_FAIL',

  START_NEW_PROGRAMME: '@programme/START_NEW_PROGRAMME',
  START_EDIT_PROGRAMME: '@programmes/START_EDIT_PROGRAMME',

  SAVE_NEW_PROGRAMME: '@programmes/SAVE_NEW_PROGRAMME',
  SAVE_NEW_PROGRAMME_SUCCESS: '@programmes/SAVE_NEW_PROGRAMME_SUCCESS',
  SAVE_NEW_PROGRAMME_FAIL: '@programmes/SAVE_NEW_PROGRAMME_FAIL',
  
  SAVE_EDIT_PROGRAMME: '@programmes/SAVE_EDIT_PROGRAMME',
  SAVE_EDIT_PROGRAMME_SUCCESS: '@programmes/SAVE_EDIT_PROGRAMME_SUCCESS',
  SAVE_EDIT_PROGRAMME_FAIL: '@programmes/SAVE_EDIT_PROGRAMME_FAIL',

  DELETE_PROGRAMME: '@programmes/DELETE_PROGRAMME',
  DELETE_PROGRAMME_SUCCESS: '@programmes/DELETE_PROGRAMME_SUCCESS',
  DELETE_PROGRAMME_FAIL: '@programmes/DELETE_PROGRAMME_FAIL',
};