export const ACTIONS = {
  LOAD_STATISTICS: '@statistics/LOAD_STATISTICS',
  LOAD_STATISTICS_SUCCESS: '@statistics/LOAD_STATISTICS_SUCCESS',
  LOAD_STATISTICS_FAIL: '@statistics/LOAD_STATISTICS_FAIL',

  LOAD_CHILDREN: '@statistics/LOAD_CHILDREN',
  LOAD_CHILDREN_SUCCESS: '@statistics/LOAD_CHILDREN_SUCCESS',
  LOAD_CHILDREN_FAIL: '@statistics/LOAD_CHILDREN_FAIL',

  LOAD_GAMES: '@statistics/LOAD_GAMES',
  LOAD_GAMES_SUCCESS: '@statistics/LOAD_GAMES_SUCCESS',
  LOAD_GAMES_FAIL: '@statistics/LOAD_GAMES_FAIL',

  SET_CHILDREN: '@statistics/SET_CHILDREN',
  SET_GAMES: '@statistics/SET_GAMES',
  SET_SINCE_DATE: '@statistics/SET_SINCE_DATE',
  SET_TILL_DATE: '@statistics/SET_TILL_DATE',
};