export const ACTIONS = {
  LOAD_USER_DATA: '@auth/LOAD_USER_DATA',
  LOAD_USER_DATA_SUCCESS: '@auth/LOAD_USER_DATA_SUCCESS',
  LOAD_USER_DATA_FAIL: '@auth/LOAD_USER_DATA_FAIL',

  LOGOUT: '@auth/LOGOUT',
};