export const ACTIONS = {
  LOAD_CHILD_INFO: '@childProfile/LOAD_CHILD_INFO',
  LOAD_CHILD_INFO_SUCCESS: '@childProfile/LOAD_CHILD_INFO_SUCCESS',
  LOAD_CHILD_INFO_FAIL: '@childProfile/LOAD_CHILD_INFO_FAIL',

  SAVE_CHILD: '@childProfile/SAVE_CHILD',
  SAVE_CHILD_ERROR: '@childProfile/SAVE_CHILD_ERROR',
  DELETE_CHILD: '@childProfile/DELETE_CHILD',

  SET_NAME: '@childProfile/SET_NAME',
  SET_SURNAME: '@childProfile/SET_SURNAME',
  SET_BIRTHDATE: '@childProfile/SET_BIRTHDATE',
  SET_PARENTPHONE: '@childProfile/SET_PARENTPHONE',
  SET_DIAGNOSIS: '@childProfile/SET_DIAGNOSIS',
  SET_INFO: '@childProfile/SET_INFO',
  SET_PROGRAMME: '@childProfile/SET_PROGRAMME',

  LOAD_PROGRAMMES: '@childProfile/LOAD_PROGRAMMES',
  LOAD_PROGRAMMES_SUCCESS: '@childProfile/LOAD_PROGRAMMES_SUCCESS',
  LOAD_PROGRAMMES_FAIL: '@childProfile/LOAD_PROGRAMMES_FAIL',

  CLEAR_FORM: '@childProfile/CLEAR_FORM',
};