export const ACTIONS = {
  SET_CURRENT_GAME: '@gamePage/SET_CURRENT_GAME',
  SET_CUURENT_GAME_ORDER: '@gamePage/SET_CURRENT_GAME_ORDER',
  
  LOAD_CURRENT_PROGRAMME: '@gamePage/LOAD_CURRENT_PROGRAMME',
  LOAD_CURRENT_PROGRAMME_SUCCESS: '@gamePage/LOAD_CURRENT_PROGRAMME_SUCCESS',
  LOAD_CURRENT_PROGRAMME_FAIL: '@gamePage/LOAD_CURRENT_PROGRAMME_FAIL',

  SAVE_RESULTS: '@gamePage/SAVE_RESULTS',

  LOAD_CHILDREN: '@gamePage/LOAD_CHILDREN',
  LOAD_CHILDREN_SUCCESS: '@gamePage/LOAD_CHILDREN_SUCCESS',
  LOAD_CHILDREN_FAIL: '@gamePage/LOAD_CHILDREN_FAIL',
};