export const ACTIONS = {
  SET_CURRENT_GAME: '@gamePage/SET_CURRENT_GAME',
  SAVE_RESULTS: '@gamePage/SAVE_RESULTS',

  LOAD_CHILDREN: '@gamePage/LOAD_CHILDREN',
  LOAD_CHILDREN_SUCCESS: '@gamePage/LOAD_CHILDREN_SUCCESS',
  LOAD_CHILDREN_FAIL: '@gamePage/LOAD_CHILDREN_FAIL',
};