export const ACTIONS = {
  LOAD_CHILDREN: '@childrenList/LOAD_CHILDREN',
  LOAD_CHILDREN_SUCCESS: '@childrenList/LOAD_CHILDREN_SUCCESS',
  LOAD_CHILDREN_FAIL: '@childrenList/LOAD_CHILDREN_FAILD',

  SET_CURRENT_PAGE: '@childrenList/SET_CURRENT_PAGE',
  SET_PAGE_ENTITIES: '@childrenList/SET_PAGE_ENTITIES',
}