export const ACTIONS = {
  SET_NAME: '@newChild/SET_NAME',
  SET_SURNAME: '@newChild/SET_SURNAME',
  SET_BIRTHDATE: '@newChild/SET_BIRTHDATE',
  SET_PARENTPHONE: '@newChild/SET_PARENTPHONE',
  SET_DIAGNOSIS: '@newChild/SET_DIAGNOSIS',
  SET_INFO: '@newChild/SET_INFO',
  SET_PROGRAMME: '@newChild/SET_PROGRAMME',

  LOAD_PROGRAMMES: '@newChild/LOAD_PROGRAMMES',
  LOAD_PROGRAMMES_SUCCESS: '@newChild/LOAD_PROGRAMMES_SUCCESS',
  LOAD_PROGRAMMES_FAIL: '@newChild/LOAD_PROGRAMMES_FAIL',

  SAVE_NEW_CHILD: '@newChild/SAVE_NEW_CHILD',
  SAVE_NEW_CHILD_ERROR: '@newChild/SAVE_NEW_CHILD_ERROR',
};